import Definitions.Def_ConcaveOTLimitModel
import Mathlib.MeasureTheory.Measure.FiniteMeasureProd
import Mathlib.MeasureTheory.Measure.Restrict

open MeasureTheory

namespace ConcaveOTLimit

/-- A dominated forward remainder stays forward after adding any nonnegative
multiple of the two crossed product measures generated by blocks whose
crossed source-target pairs are almost everywhere strictly forward. -/
theorem crossProductReroutingIsForward
    {mu nu : FiniteMeasure Real}
    (gamma : FiniteCoupling mu nu)
    (remainder rho sigma : FiniteMeasure (Real × Real))
    (c : NNReal)
    (hForward : IsForwardPlan gamma)
    (hRemainderLe :
      (remainder : Measure (Real × Real)) <=
        (gamma.plan : Measure (Real × Real)))
    (hCrossed :
      ∀ᵐ r ∂(rho : Measure (Real × Real)),
        ∀ᵐ s ∂(sigma : Measure (Real × Real)),
          r.1 < s.2 /\ s.1 < r.2) :
    ∀ᵐ z ∂((remainder +
        c •
          ((firstMarginal rho).prod (secondMarginal sigma) +
            (firstMarginal sigma).prod (secondMarginal rho)) :
          FiniteMeasure (Real × Real)) :
        Measure (Real × Real)),
      z.1 <= z.2 := by
  have crossedProductForward
      (tau upsilon : FiniteMeasure (Real × Real))
      (h :
        ∀ᵐ a ∂(tau : Measure (Real × Real)),
          ∀ᵐ b ∂(upsilon : Measure (Real × Real)),
            a.1 < b.2) :
      ∀ᵐ z ∂(((firstMarginal tau).prod
          (secondMarginal upsilon) :
            FiniteMeasure (Real × Real)) :
        Measure (Real × Real)),
        z.1 <= z.2 := by
    let cross :
        ((Real × Real) × (Real × Real)) -> Real × Real :=
      fun ab => (ab.1.1, ab.2.2)
    have hCrossMeasurable : Measurable cross := by
      dsimp only [cross]
      fun_prop
    have hProductForward :
        ∀ᵐ ab ∂((tau : Measure (Real × Real)).prod
            (upsilon : Measure (Real × Real))),
          ab.1.1 <= ab.2.2 := by
      apply
        (Measure.ae_prod_iff_ae_ae
          (measurableSet_le
            (continuous_fst.comp continuous_fst).measurable
            (continuous_snd.comp continuous_snd).measurable)).2
      filter_upwards [h] with a ha
      filter_upwards [ha] with b hab
      exact hab.le
    have hMap :
        (firstMarginal tau).prod (secondMarginal upsilon) =
          (tau.prod upsilon).map cross := by
      simpa only [firstMarginal, secondMarginal, cross,
        Prod.map_apply] using
        FiniteMeasure.map_prod_map tau upsilon
          measurable_fst measurable_snd
    rw [hMap, FiniteMeasure.toMeasure_map]
    exact
      (ae_map_iff hCrossMeasurable.aemeasurable
        (measurableSet_le measurable_fst measurable_snd)).2
        hProductForward
  have hFirstNested :
      ∀ᵐ r ∂(rho : Measure (Real × Real)),
        ∀ᵐ s ∂(sigma : Measure (Real × Real)),
          r.1 < s.2 :=
    hCrossed.mono fun _ hr =>
      hr.mono fun _ hrs => hrs.1
  have hSecondNested :
      ∀ᵐ r ∂(rho : Measure (Real × Real)),
        ∀ᵐ s ∂(sigma : Measure (Real × Real)),
          s.1 < r.2 :=
    hCrossed.mono fun _ hr =>
      hr.mono fun _ hrs => hrs.2
  have hSecondMeasurable :
      MeasurableSet
        {rs : (Real × Real) × (Real × Real) |
          rs.2.1 < rs.1.2} :=
    measurableSet_lt
      (continuous_fst.comp continuous_snd).measurable
      (continuous_snd.comp continuous_fst).measurable
  have hSecondSwapped :
      ∀ᵐ s ∂(sigma : Measure (Real × Real)),
        ∀ᵐ r ∂(rho : Measure (Real × Real)),
          s.1 < r.2 := by
    exact
      (Measure.ae_ae_comm
        (μ := (rho : Measure (Real × Real)))
        (ν := (sigma : Measure (Real × Real)))
        hSecondMeasurable).mp
        hSecondNested
  have hFirstCrossedForward :
      ∀ᵐ z ∂(((firstMarginal rho).prod
          (secondMarginal sigma) :
            FiniteMeasure (Real × Real)) :
        Measure (Real × Real)),
        z.1 <= z.2 :=
    crossedProductForward rho sigma hFirstNested
  have hSecondCrossedForward :
      ∀ᵐ z ∂(((firstMarginal sigma).prod
          (secondMarginal rho) :
            FiniteMeasure (Real × Real)) :
        Measure (Real × Real)),
        z.1 <= z.2 :=
    crossedProductForward sigma rho hSecondSwapped
  have hCrossedForward :
      ∀ᵐ z ∂(((firstMarginal rho).prod
            (secondMarginal sigma) +
          (firstMarginal sigma).prod
            (secondMarginal rho) :
          FiniteMeasure (Real × Real)) :
        Measure (Real × Real)),
        z.1 <= z.2 := by
    rw [FiniteMeasure.toMeasure_add, ae_add_measure_iff]
    exact ⟨hFirstCrossedForward, hSecondCrossedForward⟩
  have hRemainderForward :
      ∀ᵐ z ∂(remainder : Measure (Real × Real)),
        z.1 <= z.2 :=
    (MeasureTheory.ae_mono hRemainderLe) hForward
  rw [FiniteMeasure.toMeasure_add, ae_add_measure_iff]
  refine ⟨hRemainderForward, ?_⟩
  rw [FiniteMeasure.toMeasure_smul]
  exact Measure.ae_smul_measure hCrossedForward c

end ConcaveOTLimit
